import {
  Container,
  Badge,
  Link,
  List,
  ListItem,
} from '@chakra-ui/react'
import { ExternalLinkIcon } from '@chakra-ui/icons'
import { Title, Meta } from '../../components/work'
import P from '../../components/paragraph'
import Layout from '../../components/layouts/article'

const Work = () => (
  <Layout title="twitterbot">
    <Container>
      <Title>
        AI Twitter Bot <Badge>2022</Badge>
      </Title>
      <P>
        A demo twitter bot that automatically tweets content generated by artificial intelligence using GPT-3 language model by OpenAI.
      </P>
      <List ml={4} my={4}>
        <ListItem>
          <Meta>Link</Meta>
          <Link href="https://github.com/DroidBarber/ai-twitter-bot">
          github.com/DroidBarber/ai-twitter-bot <ExternalLinkIcon mx="2px"/>
          </Link>
        </ListItem>
        <ListItem>
          <Meta>PLatform</Meta>
          <span>Twitter</span>
        </ListItem>
        <ListItem>
          <Meta>Stack</Meta>
          <span>Node.js, OAuth 2.0 & Firebase</span>
        </ListItem>
      </List>
    </Container>
  </Layout>
)

export default Work
export { getServerSideProps } from '../../components/chakra'